### ISSUE TITLE
`cxxfunction` (really `compileCode`) drops `PKG_LIBS` on Windows

### ISSUE THREAD

**Issue by bgoodri** [eddelbuettel/inline#11]
On Windows, using R 4.x this example of trying to use `PKG_LIBS`
```
library(inline)
settings <- getPlugin("Rcpp")
settings$env$PKG_LIBS <- "-lfoo" # foo library does not exist
fx <- cxxfunction( signature(x = "integer", y = "numeric" ) , '
		return wrap( as<int>(x) * as<double>(y) ) ;
	', settings = settings, verbose = TRUE )
fx(2L, 5)
```
"works" when it should fail with a linker error (which it does on Debian)

> Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! /usr/bin/ld: cannot find -lfoo
collect2: error: ld returned 1 exit status

Conversely, more complicated examples where someone is trying to link against a real library on Windows fail when they should work.

If I insert a `--dry-run` argument to `R CMD SHLIB` on Windows, I get

> make cmd is
  make -f "C:/PROGRA~1/R/R-40~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-40~1.2/share/make/winshlib.mk" -f "C:/Users/Stan/Documents/.R/Makevars.win" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file20b469d76e48.dll" PKG_LIBS='2> file20b469d76e48.cpp.err.txt' WIN=64 TCLBIN=64 OBJECTS="file20b469d76e48.o"
make would use
"C:/RBuildTools/4.0/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I"C:/Users/Stan/Documents/R/win-library/4.0/Rcpp/include"        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c file20b469d76e48.cpp -o file20b469d76e48.o
if test "zfile20b469d76e48.o" != "z"; then \
  if test -e "file20b469d76e48-win.def"; then \
    echo "C:/RBuildTools/4.0/mingw64/bin/"g++ -std=gnu++11  -shared -s -static-libgcc -o file20b469d76e48.dll file20b469d76e48-win.def file20b469d76e48.o 2> file20b469d76e48.cpp.err.txt   -L"C:/PROGRA~1/R/R-40~1.2/bin/x64" -lR ; \
    "C:/RBuildTools/4.0/mingw64/bin/"g++ -std=gnu++11  -shared -s -static-libgcc -o file20b469d76e48.dll file20b469d76e48-win.def file20b469d76e48.o 2> file20b469d76e48.cpp.err.txt   -L"C:/PROGRA~1/R/R-40~1.2/bin/x64" -lR ; \
  else \
    echo EXPORTS > tmp.def; \
    "C:/RBuildTools/4.0/mingw64/bin/"nm file20b469d76e48.o | sed -n 's/^.* [BCDRT] / /p' | sed -e '/[.]refptr[.]/d' -e '/[.]weak[.]/d' | sed 's/[^ ][^ ]*/"&"/g'  >> tmp.def; \
    echo "C:/RBuildTools/4.0/mingw64/bin/"g++ -std=gnu++11  -shared -s -static-libgcc -o file20b469d76e48.dll tmp.def file20b469d76e48.o 2> file20b469d76e48.cpp.err.txt   -L"C:/PROGRA~1/R/R-40~1.2/bin/x64" -lR ; \
    "C:/RBuildTools/4.0/mingw64/bin/"g++ -std=gnu++11  -shared -s -static-libgcc -o file20b469d76e48.dll tmp.def file20b469d76e48.o 2> file20b469d76e48.cpp.err.txt   -L"C:/PROGRA~1/R/R-40~1.2/bin/x64" -lR ; \
    rm -f tmp.def; \
  fi \
fi

The `PKG_LIBS='2> file20b469d76e48.cpp.err.txt'` in the call to `R CMD SHLIB` does not look right. If I change the middle of `compileCode` on Windows to not write the errors to `errfile` by

```
cmd <- paste(R.home(component = "bin"), "/R CMD SHLIB ", 
    basename(libCFile), sep = "")
```
then I get the expected behavior

> "C:/RBuildTools/4.0/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I"C:/Users/Stan/Documents/R/win-library/4.0/Rcpp/include"        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c file20b413636b83.cpp -o file20b413636b83.o
C:/RBuildTools/4.0/mingw64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o file20b413636b83.dll tmp.def file20b413636b83.o -lfoo -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lR
C:/RBuildTools/4.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lfoo
collect2.exe: error: ld returned 1 exit status

This might be an R bug in `tools:::.shlib_internal`, but I think it could be avoided by `compileCode` invoking `system2` instead of `system` because the `system2` function has arguments for redirecting `stdout` and `stderr` to files. If anyone else is bitten by this, it can be worked around on Windows by putting the linker arguments in the `LOCAL_LIBS` environmental variable rather than `PKG_LIBS`.

**Comment by eddelbuettel** [comment]
From a (very) casual glance that is actually 

```r
  errfile <- paste( basename(libCFile), ".err.txt", sep = "" )
  cmd <- paste(R.home(component="bin"), "/R CMD SHLIB ", basename(libCFile), " 2> ", errfile, sep="")
```

in file `cfunction.R`.  None of that has been touched in ages.  

So to sum up:
- if you need to modify output from `getPlugin("Rcpp")` do not assign to `PKG_LIB`
- instead assign to `LOCAL_LIB` instead
- this may be yet another R 4.0.* change

**Comment by eddelbuettel** [comment]
Do you want to work on (and can test ...) a PR that switches to `system2` ?

**Comment by bgoodri** [comment]
I'm using the LOCAL_LIBS workaround on Windows in order to upload a working
rstan to CRAN but I can work on switching to compileCode to system2 after
that.

**Comment by eddelbuettel** [comment]
Sounds good on both counts. 

We should probably work on this; your analysis that a change in R may have caused this is probably right, and it may be worth fixing.  But you have access to a better setup for testing :) so I would love for you to lead this.  No urgency but we should probably get to it "at some point".
