### ISSUE TITLE
CRAN failures

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/inline#21]
KH emailed

> Please see the problems shown on <https://cran.r-project.org/web/checks/check_results_inline.html>.
> 
> Please correct before 2021-05-27 to safely retain your package on CRAN.

@jranke I may need your help here as the issues, following the link above appear to end in the tests for `moveDLL` applied to `quadfun`:

```
Running test_utilities.R.............. 3 tests [0;32mOK [0m \
    Error in .Primitive(".C")(<pointer: (nil)>, n = as.integer(n), x = as.double(x)) :
    NULL value passed as symbol address
  Calls: <Anonymous> ... eval -> expect_identical -> fun -> quadfn -> <Anonymous>
  Execution halted
```

I'll start by trying to reproduce on RHub.

**Comment by eddelbuettel** [comment]
I can reproduce via `library(rhub); check(".", platform=c("fedora-clang-devel"))` and have a "fix" in that I will simply skip those if the OS is not Debian (borrowing code [from this segment in `anytime`](https://github.com/eddelbuettel/anytime/blob/b4fda468ae0a13c60fec5d94d1d063d596070793/R/init.R#L61-L76) ). I am of course open to a better "permanent" solution if you can come up with one.

**Comment by eddelbuettel** [comment]
That code is now in [this branch](https://github.com/eddelbuettel/inline/tree/bugfix/tame_tests).

**Comment by jranke** [comment]
I am currently travelling, but I will see if I can solve the underlying problem on Monday.

**Comment by eddelbuettel** [comment]
Thanks for the feedback.  We can wait a few days.  

We could also upload the fix now, and then have no time pressure to work on the underlying issue.

**Comment by jranke** [comment]
The CRAN checks now show test failures on Debian as well. I just updated my local R-devel on Debian bullseye and could reproduce the failure locally, so I can start tracking it down.

**Comment by eddelbuettel** [comment]
Good catch!  I just updated r-devel to SVN r80309 as of today here, and that makes 0.3.17 fail for me too (and renders my local 0.3.17.1 invalid as 'test only on Debian' no longer works, it really is an R-devel issue.

So maybe wholesale suppression of moveDLL tests unless opted in (locally, by you or me; or unless R version <= 4.0.5) is safest unless you actually find a fix ...

**Comment by eddelbuettel** [comment]
I presume the mail below was triggered by you.  Hint: change Maintainer: to your email to get the reply. I also *strongly* suggest to not use release versions.  My draft is 0.3.17.1, not 0.3.18.

```
From: ligges@statistik.tu-dortmund.de             
To: edd@debian.org                                         
Cc: ligges@statistik.tu-dortmund.de                
Subject: winbuilder: Package inline_0.3.18.tar.gz has been checked and built    

Dear package maintainer,

this notification has been generated automatically.
Your package inline_0.3.18.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/LZ7m7H96A16F
The files will be removed after roughly 72 hours.
Installation time in seconds: 5
Check time in seconds: 152
Status: OK
R version 4.0.5 (2021-03-31)

All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)
```

**Comment by eddelbuettel** [comment]
@jranke :-/  "No rest for the wicked" as they say.  

Version 0.3.18 still fails on M1mac (follow the link to see it is 0.3.18) and failed on Slowlaris:  https://cloud.r-project.org/web/checks/check_results_inline.html

Should we play it a little more defensively and ... just turn those `moveDLL()` tests off?  No point in picking fights in which our nose gets bloodied time after time _on systems we have do not have real test access_.
