### ISSUE TITLE
readDynLib not initially recognized

### ISSUE THREAD

**Issue by MPagel** [eddelbuettel/inline#8]
In R 3.4.3
```
library("inline")
readDynLib()
```

> Error in readDynLib() : could not find function "readDynLib"

`packageVersion("inline")`

> [1] ‘0.3.14’

defining the function to be the same as in this repo seems to solve it.  Is utilities.R not fully linked from the package?

**Comment by eddelbuettel** [comment]
Can you please refresh my memory of why that 
- is a problem in general (ie what is readDynLib ?)
- why you think it is a problem in the package / repo as this is not a symbol we use, define or export

**Comment by eddelbuettel** [comment]
So it would appear we have an R function readDynLib that is not exported.  Ok then.   You can always use three colons to get to such a function (whether or not you first attach the package via `library(inline)`:

```
> inline:::readDynLib()
Error in basename(file) : argument "file" is missing, with no default
> 
```

All this came from a pull request I accepted in late 2014.  Nobody seem to have missed the function so far.  If you don't mind I think I'll just close this.
