### ISSUE TITLE
cfunction could get `cargs` argument corresponding to CFLAGS

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/inline#9]
In the `cfunction` there are `cppargs/cxxargs` arguments that refers to `CPPFLAGS/CXXFLAGS` but there is no `cargs` that would refer to `CFLAGS`. FR to add that one.

**Comment by eddelbuettel** [comment]
You can use `CPPFLAGS` to pass arguments to the C compiler. That should be good enough, no?

**Comment by jangorecki** [comment]
@eddelbuettel yes it works, but it is counter intuitive.

**Comment by eddelbuettel** [comment]
That is in the eye of the beholder. I (mis)used CPPFLAGS for CFLAGS for many years. We do not split preprocessor and compiler for C -- it is one call.

Changing this now would change the calling interface. I'd rather not for a small cosmetic change.  I suggest we close this and move on.    Moreover, all this does is set an environment variable which you could set outside of `cfunction` too.

My main point is there: there is no (real) functional deficiency here.
